### PR TITLE
Update old DOI-URLs 

### PR DESCRIPTION
**Pull request by lvlzay**
see diff 
https://www.doi.org/doi_handbook/3_Resolution.html#3.8

### CODE REVIEW

**Comment by remram44** [comment]
Hi @lvlzay, thanks for the update. I'm confused -- are you and @bathmer the same person? See #236

**Comment by lvlzay** [comment]
Hi @ remram44  sorry for the confusion! @bathmer and I were at a carpentry course and we were all doing the same thing.

**Comment by remram44** [comment]
You submitted the same change at the exact same second, so I got very surprised. I'm going to close in favor of #236, since it was technically first (and doesn't have the whitespace changes).

Thank you for contributing!

**Comment by lvlzay** [comment]
@remram44 must have been after the tutor said "and now one of you should commit it" (*´◡`) Sorry again!

**Comment by remram44** [comment]
No problem! Just... same second :thinking: wow

**Comment by katrinleinweber** [comment]
I'm in part responsible for this confusion, sorry. We used this example in a Git & GitHub tutorial. Please merge either #236 or this.

**Pull request closed without merging**
