### PR TITLE
Update styles

### PR DESCRIPTION
**Pull request by fmichonneau**
this pull request brings the latest version of the lesson template.

### CODE REVIEW

**Comment by remram44** [comment]
Buid fails with:
```
  Liquid Exception: Could not find document 'aio.md' in tag 'link'. Make sure
the document exists and the path is correct. in /_layouts/base.html
```

**Comment by remram44** [comment]
Since this seems to happen everywhere (https://github.com/swcarpentry/sql-novice-survey/pull/231) maybe something needs to be fixed upstream? cc @rgaiacs

**Comment by rgaiacs** [comment]
> Build fails with:
>
> ~~~
> Liquid Exception: Could not find document 'aio.md' in tag 'link'. Make sure
the document exists and the path is correct. in /_layouts/base.html
> ~~~

The `aio.md` file is created by `bin/lesson_initialize.py` as many of the other files. This create a issue when upgrade to a new version that you need to copy lines from `bin/lesson_initialize.py` into the file. If you want to copy the file from another place you can use https://raw.githubusercontent.com/swcarpentry/lesson-example/gh-pages/aio.md.

> Since this seems to happen everywhere maybe something needs to be fixed upstream?

Nothing to fix upstream. The release notes of v9.2.0, https://github.com/swcarpentry/styles/releases/tag/v9.2.0, where the `aio.md` was introduced mentions the need to create the file. Because some lessons were using a version older that v9.2.0 they have to deal with this now.

**Comment by remram44** [comment]
I see! Maybe those release notes should be linked from pull requests? As a new maintainer, I didn't know where to find that (in fact I don't what version of the styles this lesson is using...)

What about including the migration step history in the code, in a markdown file? That way the diff will clearly show which steps are new and need to be followed.

**Comment by rgaiacs** [comment]
> Maybe those release notes should be linked from pull requests?

I believed that I liked the notes when I informed maintainers that v9.2.0 was available. This was a long time ago. And Data Carpentry lessons weren't using the template at that time.

> As a new maintainer, I didn't know where to find that (in fact I don't what version of the styles this lesson is using...)

I created https://github.com/swcarpentry/styles/issues/237 to facilitate it for future maintainers.

> What about including the migration step history in the code, in a markdown file?

Extra work to maintain things updated in different places.

Thanks for all the feedback.

**Pull request merged**
