### PR TITLE
Added Solutions for challenges, re-worded one challenge; re-worked th…

### PR DESCRIPTION
**Pull request by nek555**
…e Execution order section

This PR is part of instructor training checkout.   I responded to Issue 179 and added solutions to the challenge questions.    I tried to use formatting similar to what I saw in the Open Refine for Ecology lessons.   I also changed the wording on one challenge question from "produce a table" to "write a query"  . this is similar to the other challenges.   Produce a table could be interpreted to mean use the "create table as SELECT" functionality of the DBMS to materialize the result set, and that's not what's intended here.   I also changed the "Order of Execution" section.  I do not think it is correct that sorting occurs before column selection (on most DBMS) and in any case, it seems like the advanced topic of how the optimizer work is irrelevant for intro learners. SQL is a declarative language and the point of that is not needing to know how the DBMS engine works.  I think the point of this section is to illustrate that different columns may be used in each clause of the SQL statement (within limits) and that's how I re-wrote this section.    This re-write was not included in Issue 179, I'm adding as my own extra contribution.  Please feel free to send this back to me if I am mistaken in my views.

I was not entirely clear on the kind of markdown language being used.  Therefore, some things are not formatted as I wish.  In particular, the SQL statements in the solution blocks are not formatted as code blocks.  I tried using 4 spaces to trigger the code block format, but that does not work inside the solution block.  I would want the SQL to appear with better formatting, ie each clause starting on a new line, but I don't see how to do that within the solution block.   If you can fix that for me, and let me know how to fix that, I would greatly appreciate it.   Also, I was using grip to look at the markdown in my browser, that was pretty helpful, but it is not the same as the rendering done by Carpentry, so I can't see exactly how my lesson will be formatted.

Thanks.

### CODE REVIEW

**Comment by orchid00** [comment]
Hello @nek555, those are all great suggestions! thanks for your contribution, that is how we improve all of the lessons. I will comment on your suggestions and we can work from there. For next time, please focus the updates in one part so it is easier to merge pull requests, and also answer to independent issues.

**Comment by orchid00** [comment]
Hi @nek555, you can write your queries here, I am happy to help moving forward. If you could please address my comments, I am happy to merge.

**Comment by orchid00** [comment]
Hi @nek555 any change you could fix the pull request in the next week? that will be awesome! Otherwise, I will have to close this pull request due to lack of progress after review.

**Comment by ErinBecker** [comment]
Exercise solutions have been added: https://github.com/datacarpentry/sql-ecology-lesson/pull/215

**Pull request closed without merging**
