### PR TITLE
clarify challenge, full sentences

### PR DESCRIPTION
**Pull request by ErinBecker**
The first research question in the first challenge wasn't very focused. I think this one gives the learner a clearer picture of how they would go about answering that research question manually, which can then be contrasted more clearly with an approach using a database. 

I also made the bullet point items under "why use relational databases" full sentences.

### CODE REVIEW

**Comment by orchid00** [comment]
Hi Erin, 
Thanks for the suggestions.
I think the idea of the first question is to use a condition to get the rows > 2000. 
What information can I learn about Dipodomys species in the 2000s, over time? So in your suggestion will be good to include that too. If you could add that I will merge your request.
Your second suggestions on relational databases are excellent, thanks for that.

**Comment by ErinBecker** [comment]
@orchid00 Thanks for looking at my suggestions. I still think the research question "what can I learn" is pretty vague and hard for a learner to know what concrete steps they would take to answer it given the input files. I added that question back to the challenge as suggested.

**Comment by ErinBecker** [comment]
@tpoisot Thanks for merging. Unfortunately, the bullet points under "Why use relational databases" aren't displaying properly. They preview properly, but the line breaks aren't correct on the live site.

**Comment by tpoisot** [comment]
Can you give me the link to the page?

**Comment by ErinBecker** [comment]
http://www.datacarpentry.org/sql-ecology-lesson/00-sql-introduction.html

**Pull request merged**
