### PR TITLE
Add discussion of HAVING

### PR DESCRIPTION
**Pull request by tpoisot**
As suggested in #53 -- a short paragraph on `HAVING` in lesson 2.

Comments / feedback welcome.

No challenge yet.

### CODE REVIEW

**Comment by tpoisot** [comment]
There is a challenge now.

**Comment by waveform80** [comment]
Looks good! One minor nit-pick (sorry! I do seem to be the annoying one...): HAVING's ability to use column correlations is non-standard and not universally supported (Postgres doesn't support it for one).

This somewhat ties into its status as the one redundant clause in SELECT; all the rest (WITH, SELECT, FROM, WHERE, GROUP BY and ORDER BY) are required for a complete query language, but in all cases HAVING is merely a shortcut for a WHERE referencing a sub-query, i.e. there's no difference between:

```sql
SELECT species_id, COUNT(*)
FROM surveys
GROUP BY species_id
HAVING COUNT(surveys.species_id) > 10
```

And:

```sql
SELECT species_id, occurrences
FROM (
    SELECT species_id, COUNT(*) AS occurrences
    FROM surveys
    GROUP BY species_id
)
WHERE occurrences > 10
```

Some murky corner of my memory recalls that SQL originally lacked sub-queries and HAVING was added as a bit of a hack to make certain kinds of queries possible. Sorry, rambling again...

Is it worth mentioning explicitly that HAVING is (effectively) processed after GROUP BY while WHERE is processed before (to explain why HAVING gets to use aggreate functions while WHERE doesn't)? For that matter is it worth mentioning the semantic processing order of queries generally (WITH, FROM, WHERE, GROUP BY, HAVING, SELECT, ORDER BY - which also explains why correlations are generally only available to ORDER BY - because SELECT is processed very late)?

**Comment by orchid00** [comment]
@waveform80 I think you just nailed the purpose of the clause HAVING: HAVING is (effectively) processed after GROUP BY while WHERE is processed before. ---Very worth mentioning :) to explain why HAVING gets to use aggregated functions while WHERE doesn't.

**Comment by tpoisot** [comment]
The differences in dialect across SQL implementations is going to be an issue... I think for 90% of the learners, they will be interested in using SQLite, since it has ~ no setup. So I am comfortable teaching things that will only work with SQLite, under the assumption that people using pgSQL, etc, will already be more advanced and will have read on the standards.

On the other hand, your point about *when* `HAVING` works is :+1: . I'll adress this in a commit very soon.

**Comment by waveform80** [comment]
Fair point on SQLite - it's the favoured engine so it's okay to teach things specific to it.

On your extra commits - there's a little issue: SELECT is indeed *written* first but it's not *processed* first (in fact it's almost last). The semantic execution order in SQL queries is:

1. **FROM** - firstly all tables mentioned in FROM are retrieved and joined as specified by the various JOIN clauses (if any). If tables are listed with "," separators these are semantically equivalent to CROSS JOIN (cartesian products). Note: the result is a single table (the potentially huge result of all aforementioned joins including all columns from all joined tables).
2. **WHERE** - next the result is filtered for the condition (if any) specified in the WHERE clause. Only rows for which the condition evaluates to TRUE are kept (important: if the condition evaluates to NULL or FALSE the row will be excluded). Note: I say condition rather than conditions because the WHERE clause only specifies a single condition (although that condition may contain predicates combined with the boolean AND, OR operators).
3. **GROUP BY** - if this clause is specified, the result set is collapsed to unique combinations of the columns listed. For columns not listed, consider their values to form multi-value "bags" associated with the key (the listed columns). Note: aggregates are not yet calculated - we're just setting up the bags that we can calculate them from. This is also why most engines ban selecting directly from non-listed columns: which value does it pick from the bag? The answer is non-deterministic.
4. **HAVING** - if specified, the result set is now filtered by the condition specified. Aggregates may be calculated from the bags of values at this stage.
5. **SELECT** - finally, columns of the result set are projected according to the list specified by the SELECT statement. More aggregates may be calculated at this stage, columns may be discarded, renamed, or recalculated according to the expressions in the list.
6. **ORDER BY** - if specified, the final result set is now sorted according to this clause.

I've left out WITH in the list above as it's just a case of executing the same list for all sub-queries first (unless you want to get into recursive queries ... but let's not go there :).

Why does the syntactic order not match the semantic order (i.e. why on earth does SELECT come first in the syntax and near last in the processing)?! You'd have to ask the early designers of SQL, but bear in mind it was originally designed as an end user interface (really!) so there was probably an element of trying to make it read like English (oh dear), rather than a programming language.

I should also mention this is only the *semantic* order. Engines are free to execute a query in any order they like (or even ignore entire parts of a query), provided the result they produce is equivalent to execution of this order. For example, if I write:

```sql
WITH d AS (
  SELECT * FROM foo
)
SELECT * FROM bar
```

Any sane engine would say to itself: "Dave's an idiot - he's written an entire sub-query (d) which he hasn't even used in the main query - I'll just execute `SELECT * FROM bar` and be done with it". Perfectly reasonable as it'll produce the same result.

I don't know whether this is all too complex for a course like this though. It may just be enough to point out the ordering of WHERE, GROUP BY, and HAVING without having to explain SELECT's weird positioning.

**Comment by tpoisot** [comment]
I think most of the details are *way* too advanced for this course (but that's maybe good reference material for instructors? I certainly did learn a thing or three). I replaced "evaluated" by "written", which should allow to (1) explain how to write things while (2) glossing over the details of what goes on under the hood.

**Comment by tpoisot** [comment]
**MERGED**

If there are still improvements, I assume they will be minor ones, and can be done in smaller PRs.

**Pull request merged**
